# Generated by Django 2.2.3 on 2020-05-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Naboform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infonabo',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
