# Generated by Django 2.2.3 on 2020-05-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Naboform', '0002_auto_20200513_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Infonabo',
        ),
    ]
