# Generated by Django 2.2.3 on 2020-05-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Naboform', '0003_delete_infonabo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infonabo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('entrada', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=60)),
                ('time', models.TimeField()),
            ],
        ),
    ]
